version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
    - POSTGRES_RANDOM_ROOT_PASSWORD=yes
    - POSTGRES_DATABASE=db
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef